services:

  nginx:
    image: nginx:1.27.5-alpine
    ports:
     - "80:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  server:
    build: ./server
    command: npm run start
  
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.9.0-alpine
    environment:
      OAUTH2_PROXY_PROVIDER: ${OAUTH2_PROXY_PROVIDER}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET}"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost/oauth2/callback"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
